### ISSUE TITLE
Quota without value but even shows image of the value.

### ISSUE THREAD

**Issue by MaxAlmeida** [VisualizeMobile/AKANAndroidTest#17]
To reproduce the bug:
- Vinicius Gurgel 
  - May 2015
  - airline tickets

**Comment by ArthurJahn** [comment]
This quota has a value. But it's negative. This happens when a congressman presents a note that can't be paid by the government, so the congressman has to pay it. If this quota has already been released to the system, it needs to be corrected, so they release a negative cost to abate the value

**Comment by ArthurJahn** [comment]
We have to figure out a way to show these quotas.
