### ISSUE TITLE
Url Has No Column Named UPDATE_VERIFIER_URL

### ISSUE THREAD

**Issue by Thaiane** [VisualizeMobile/AKANAndroidTest#8]
# Url Has No Column Named UPDATE_VERIFIER_URL
## Description

**English:** in `testLocalDatabaseIsEmpty()` and `testLocalDatabaseIsNotEmpty()` it observed by log that a column is missing in database.

**Portuguese:** no `testLocalDatabaseIsEmpty()` e `testLocalDatabaseIsNotEmpty()` observou-se por meio do _log_ que uma coluna está faltando uma coluna no banco de dados.
## Suite Test JUnit

![screenshot2](https://cloud.githubusercontent.com/assets/5108244/7960004/9969cb54-09d3-11e5-8aff-2dd81b663503.png)
## Failure Trace

![screenshot3](https://cloud.githubusercontent.com/assets/5108244/7960010/a1c99d6a-09d3-11e5-92b5-cd08db7f5deb.png)
## Log

![screenshot1](https://cloud.githubusercontent.com/assets/5108244/7960013/aee5848c-09d3-11e5-991c-3355646b83db.png)
## Suggested Repair

**English:** apparently just add this column in Url table. This is done inside the class `UrlDao`.

**Portuguese:** aparentemente basta adicionar essa coluna na tabela Url. Isso é feito dentro da classe `UrlDao`.

**Comment by TomazMartins** [comment]
It is more complicated than it seems.You're not just add a column in the class `UrlDao`. The error insists. I'm not finding solution at the time.

The error have origin in method `insertValidEntitiesToLocalDatabe()`, when we try to insert a Url into database.
